# Database - vul jouw gegevens in
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow_db
spring.datasource.username=root
spring.datasource.password=VERJOUW_WACHTWOORD_HIER

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=verander-dit-naar-een-lang-geheim-woord-minimaal-32-tekens
jwt.expiration=86400000

# App naam
spring.application.name=taskflow
